### ISSUE TITLE
Überhaupt keine Vermittlungscodes verfügbar, breche ab.

### ISSUE THREAD

**Issue by tmalsburg** [lk3de/impftermin-checker#15] opened 2021-06-06 08:49 UTC
I'm getting the output below:
```
Öffne Webseite für "Impfzentrum Ludwigsburg" (Vermittlungscode: ohne): https://005-iz.impfterminservice.de//impftermine/service?plz=71636 (Zeit: 2021-06-06 10:45:55)
Akzeptiere Cookie-Banner.
Klicke auf "Nein, Anspruch prüfen".
Überhaupt keine Vermittlungscodes verfügbar, breche ab.
Warte 10s vor dem nächsten Code.
```
What's the meaning of _Überhaupt keine Vermittlungscodes verfügbar, breche ab._ and how can I fix it?

My data sets look like this:

``` json
      {
         "name": "Impfzentrum Klinikum Stuttgart in der Liederhalle (Hegel-Saal)",
         "plz": "70174",
         "Ort": "Stuttgart",
         "url": "002-iz.impfterminservice.de/",
         "Adresse": "Berliner Platz 1",
         "age": 44,
         "notification_emails": ["xxx@xxx.de"]
      },
```

**Comment by lk3de** [comment] 2021-06-06 09:31
_Überhaupt keine Vermittlungscodes verfügbar_ is logged if the page says this:

![grafik](https://user-images.githubusercontent.com/24473659/120919471-0da3fe00-c6ba-11eb-9bc5-d47e964ff2ac.png)

There is unfortunately no fix for this, it just means that you currently cannot request any Vermittlungscode at all for your selected Impfzentrum. This is not a bug in the tool, it's just the current overall situation. ☹️ 

If you are on Windows, you can try the [Alternative option to get a Vermittlungscode instantly](https://github.com/lk3de/impftermin-checker#alternative-option-to-get-a-vermittlungscode-instantly-windows-only).

By the way: you can safely remove the `Ort` and `Adresse` elements in your JSON object. They are not used by the tool at all. 🙂

**Closed by lk3de** 2021-06-06 09:31 UTC

**Comment by SilvesterSchneider** [comment] 2021-06-06 09:34
> If you are on Windows, you can try the [Alternative option to get a Vermittlungscode instantly](https://github.com/lk3de/impftermin-checker#alternative-option-to-get-a-vermittlungscode-instantly-windows-only).

I think this option is not possible any more.
They changed something on the request maybe.
If i try to intersect the request i see *Bad Request* in Fiddler.

**Comment by lk3de** [comment] 2021-06-06 09:45
Oh okay, I didn't know that...

I'm afraid that in this case there is no other solution but just trying again and again.

**Comment by tmalsburg** [comment] 2021-06-06 10:03
Thanks for the explanation.

**Comment by lk3de** [comment] 2021-06-06 23:12
@SilvesterSchneider I just tried the Fiddler method by myself and it worked with a little bit of extra effort. You need to enable automatic breakpoints after responses and complete the browser's request manually through Fiddler. Check out the updated [Readme section](https://github.com/lk3de/impftermin-checker#recommended-option-to-get-a-vermittlungscode-instantly-windows-only). Hope this helps 😃
